deployment:
  namespace: green-ecolution-project-website-dev
  name: project-website-dev
  replicaCount: 1
  image:
    repository: ghcr.io/smartcityflensburg/project-website-dev
    pullPolicy: Always
    tag: "af5d56c"
ingress:
  enabled: true
  hosts:
    - host: dev.green-ecolution.de
      paths:
        - path: /
          pathType: ImplementationSpecific
          service:
            name: project-website
            port: 80
  tls: []
