deployment:
  namespace: green-ecolution-project-website
  name: project-website
  replicaCount: 1
  image:
    repository: ghcr.io/smartcityflensburg/project-website
    pullPolicy: Always
    tag: latest
