deployment:
    namespace: project-website
    name: project-website
    replicaCount: 1
    image:
        repository: ghcr.io/smartcityflensburg/project-website
        pullPolicy: Always
        tag: v1.0.0

ingress:
    enabled: true
