deployment:
    namespace: project-website
    name: project-website
    replicaCount: 1
    image:
        repository: ghcr.io/green-ecolution/project-website
        pullPolicy: Always
        tag: v1.0.1

ingress:
    enabled: true
