deployment:
  namespace: green-ecolution-project-website-stage
  name: project-website-stage
  replicaCount: 1
  image:
    repository: ghcr.io/smartcityflensburg/project-website-stage
    pullPolicy: Always
    tag: latest

ingress:
  enabled: true
  hosts:
    - host: stage.green-ecolution.de
      paths:
        - path: /
          pathType: ImplementationSpecific
          service:
            name: project-website
            port: 80
  tls: []
