deployment:
    annotations: {}
    labels: {}
    namespace: project-website
    name: project-website
    replicaCount: 1
    image:
        repository: ghcr.io/smartcityflensburg/project-website
        pullPolicy: Always
        tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
    name: project-website
    type: ClusterIP
    port: 80
    protocol: TCP

ingress:
    enabled: false
    name: project-website-ingress
    className: "traefik"
    annotations:
        cert-manager.io/cluster-issuer: cert-manager
        kubernetes.io/ingress.class: traefik
    hosts:
        - name: green-ecolution.de
          paths:
              - path: /
                pathType: Prefix
                backend:
                    serviceName: project-website
                    servicePort: 80
    tls:
        enabled: true
        secretName: green-ecolution-de-tls

resources: {}

livenessProbe:
    httpGet:
        path: /
        port: http

readinessProbe:
    httpGet:
        path: /
        port: http

volumes: []
volumeMounts: []

nodeSelector: {}
