deployment:
  annotations: {}
  labels: {}
  namespace: green-ecolution-project-website
  name: project-website
  replicaCount: 1
  image:
    repository: ghcr.io/smartcityflensburg/project-website
    pullPolicy: Always
    tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  name: project-website
  type: ClusterIP
  port: 80
  protocol: TCP

ingress:
  name: project-website
  enabled: true
  className: "traefik"
  annotations: 
    - "kubernetes.io/ingress.class: traefik"
  hosts:
    - host: green-ecolution.de
      paths:
        - path: /
          pathType: ImplementationSpecific
          service:
            name: project-website
            port: 80
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

volumes: []
volumeMounts: []

nodeSelector: {}

