name: Build and Test Staging
"on":
  push:
    branches:
      - release/*
      - hotfix/*

jobs:
  build_stage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build stage
        run: yarn build:stage
