name: Build and Push Docker Image Develop
"on":
  push:
    branches:
      - develop

jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from branch name (for release branches)
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: "${{ github.repository }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.docker/Dockerfile.dev
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}-dev:latest, ghcr.io/${{ env.REPO_LC }}-dev:${{ env.COMMIT_SHA }}

  change_helm_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from branch name (for release branches)
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV

      - name: "Setup yq"
        uses: dcarbone/install-yq-action@v1.1.1
        with:
          version: "v4.42.1"
          force: true

      - name: Initialize mandatory git config
        run: |
          git config user.name "Cedrik Hoffmann"
          git config user.email github@choffmann.io

      - name: Bump version in develop/values.yaml
        run: yq -i '.deployment.image.tag=strenv(env.COMMIT_SHA)' ./k8s/values/develop.yaml

      - name: Commit k8s values files
        id: make-commit
        run: |
          git add ./k8s/values/develop.yaml
          git commit --message "Update dev image"

          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push changes
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
